Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [2]:
import numpy as np

In [5]:
x = np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Write a NumPy program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [8]:
x = np.arange(12,38)
y = x[::-1]
print(y)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
    
[[0 1 0 1 0 1 0 1]
..........
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

In [17]:
x = np.zeros(64).reshape(8,8)
print(x)
print()
x[::2, 1::2],x[1::2, ::2]=1,1
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [18]:
import numpy as np
def checkerboard(n):
    return np.indices(n).sum(axis = 0) % 2
checkerboard((8,8))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array.
Expected Output:
Original Array:
['clarusway' 'data' 'science' 'bootcamp' 'is' 'the' 'best']

Capitalized:  ['Clarusway' 'Data' 'Science' 'Bootcamp' 'Is' 'The' 'Best']
Lowered:  ['clarusway' 'data' 'science' 'bootcamp' 'is' 'the' 'best']
Uppered:  ['CLARUSWAY' 'DATA' 'SCIENCE' 'BOOTCAMP' 'IS' 'THE' 'BEST']
Swapcased:  ['CLARUSWAY' 'DATA' 'SCIENCE' 'BOOTCAMP' 'IS' 'THE' 'BEST']
Titlecased:  ['Clarusway' 'Data' 'Science' 'Bootcamp' 'Is' 'The' 'Best']

In [1]:
import numpy as np
a = np.array(['clarusway', 'data', 'science', 'bootcamp', 'is', 'the', 'best'], dtype = str)
print('Capitalized: ', np.char.capitalize(a))
print('Lowered: ', np.char.lower(a))
print('Uppered: ', np.char.upper(a))
print('Swapcased: ', np.char.swapcase(a))
print('Titlecased: ', np.char.title(a))

Capitalized:  ['Clarusway' 'Data' 'Science' 'Bootcamp' 'Is' 'The' 'Best']
Lowered:  ['clarusway' 'data' 'science' 'bootcamp' 'is' 'the' 'best']
Uppered:  ['CLARUSWAY' 'DATA' 'SCIENCE' 'BOOTCAMP' 'IS' 'THE' 'BEST']
Swapcased:  ['CLARUSWAY' 'DATA' 'SCIENCE' 'BOOTCAMP' 'IS' 'THE' 'BEST']
Titlecased:  ['Clarusway' 'Data' 'Science' 'Bootcamp' 'Is' 'The' 'Best']


In [ ]:
Soru yukarıdaki array içindeki kelimelerden cümle kurup ilk harfleri büyük olacak şekilde string bir çıktı alalım

In [29]:
import numpy as np
a = np.array(['clarusway', 'data', 'science', 'bootcamp', 'is', 'the', 'best'],dtype=str)
b = [0, 4, 5, 6, 1, 2, 3]
print(a[b])   # fancy index.


['clarusway' 'is' 'the' 'best' 'data' 'science' 'bootcamp']


In [39]:
import numpy as np
a = np.array(['clarusway', 'data', 'science', 'bootcamp', 'is', 'the', 'best'],dtype=str)
b = a[0]
c = a[4], a[5], a[6]
d = a[1], a[2]
b, c ,d   # fancy index.

('clarusway', ('is', 'the', 'best'), ('data', 'science'))

In [ ]:
Write a NumPy program to count a given word in each row of a given array of string values.
Sample output:
Original array of string values:
[['Python' 'NumPy' 'Exercises']
['Python' 'Pandas' 'Exercises']
['Python' 'Machine learning' 'Python']]
Count 'Python' row wise in the above array of string values:
[[1 0 0]
[1 0 0]
[1 0 1]]

In [18]:
import numpy as np
a = np.array([['Python', 'NumPy', 'Exercises'],
              ['Python', 'Pandas', 'Exercises'],
              ['Python', 'Machine learning', 'Python']])

print(np.char.count(a,'Python'))


[[1 0 0]
 [1 0 0]
 [1 0 1]]


In [22]:
import numpy as np
a = np.array([['Python', 'NumPy', 'Exercises'],
              ['Python', 'Pandas', 'Exercises'],
              ['Python', 'Machine learning', 'Python']])


np.array(a[:,:] == 'Python').argmax()




0

In [23]:
import numpy as np
a = [['Python', 'NumPy', 'Exercises'],
     ['Python', 'Pandas', 'Exercises'],
     ['Python', 'Machine learning', 'Python']]

b = np.array(a)
b.shape[0]
for i in range(b.shape[0]):
    for j in range(b.shape[0]):
        if b[i,j] == 'Python':
            b[i,j] = 1
        else:
            b[i,j] = 0
print(b)

[['1' '0' '0']
 ['1' '0' '0']
 ['1' '0' '1']]


In [14]:
import numpy as np
a = np.array(['2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017',
       '2018', '2019', '2020'], dtype=int)
a

array([2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020])

In [15]:
a = np.arange(2010,2021)
a

array([2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020])