In [1]:
import time

In [2]:
import numpy as np

In [3]:
start_time = time.time()   # şimdiki zaman
A = np.arange(1000000)   # bir milyon elemanlı bir ndarray oluşturduk.
A**2
time_1 = time.time()-start_time   # A nın oluşturulma süresi

start_time_2 = time.time()
l = range(1000000)
[i**2 for i in l]
time_2 = time.time() - start_time_2

print(time_2/time_1)


120.37420698181344


In [4]:
import numpy as np

In [5]:
x = np.array([4,5,6,7])
print(x)

[4 5 6 7]


In [6]:
print(type(x))

<class 'numpy.ndarray'>


In [7]:
print(x.shape)  #her eksendeki eleman sayısını dönüyor. Tek bir rakamlı tuple gösterildiğinde bunun için virgül konuyor.

(4,)


In [8]:
print(x.size)  #nd arrayin toplam eleman sayısını gösteriyor.

4


In [9]:
print(x.ndim)  #nd arrayin boyutunu veriyor.

1


In [10]:
print(x.nbytes) #veriyi depolamak için kullanılan alanı veriyor.

16


In [12]:
print(x.dtype)   #elemanların veri tipini belirtir.

int32


In [13]:
y = np.array([[1,2,3,],[4,5,6]]) #iki boyutlu liste oluşturduk. Yani liste içinde liste gibi düşünülebilir.

In [15]:
print(y)
print(type(y))
print(y.shape)
print(y.size)
print(y.ndim) 
print(y.nbytes)
print(y.dtype)  

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
6
2
24
int32


In [19]:
z = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [20]:
print(z)
print(type(z))
print(z.shape)
print(z.size)
print(z.ndim) 
print(z.nbytes)
print(z.dtype) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>
(2, 2, 2)
8
3
32
int32


In [21]:
x = np.array([1,2,3])
print(x.dtype)

int32


In [22]:
y = np.array([1,"2",3])
print(y.dtype)              #U11 11 karakterli bir unicode bir string olduğunu gösteriyor. Ve buradaki tüm elemanları string olarak görüyor. Accending deniyor buna.

<U11


In [23]:
z = np.array([1,2.0,3])
print(z.dtype)          # Burada ise elemanların veri tipini float a çeviriyor. Buna UPCASTING deniyor. 

float64


In [25]:
import numpy as np

In [28]:
x = np.array([3,4.0,5])
print(x)
print(x.dtype)   # Burada upcasting yaparak int32 yerine float64 kullanıyor.

[3. 4. 5.]
float64


In [27]:
# There are 5 basic numerical types representing booleans (bool), integers (int), unsigned integers (uint) floating point (float) and complex. 

In [34]:
import numpy as np

In [42]:
x = np.array([3,4,5], dtype=int)   #bu şekilde veri tipini kendimizi dışarıdan belirtiyoruz.
print(x)
print(x.dtype)

[3 4 5]
int32


In [41]:
y = np.array([3,4,5], dtype=float)
print(y)
print(y.dtype)

[3. 4. 5.]
float64


In [40]:
z = np.array([3,4,5], dtype=complex)
print(z)
print(z.dtype)

[3.+0.j 4.+0.j 5.+0.j]
complex128


In [39]:
x = np.array([3.2,4.5,5.8], dtype=int)   
print(x)
print(x.dtype)

[3 4 5]
int32


In [43]:
x = np.array([1,2,3,4], dtype=float) 
print(x)
print(x.dtype)

[1. 2. 3. 4.]
float64


In [44]:
x = np.array(x, dtype=complex)   #veri tipini değiştirmek için kullanıyoruz.
print(x)
print(x.dtype)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex128


In [45]:
x = x.astype(complex)  # veri tipini değiştirmek için astype metodunu da kullanabiliriz.
print(x)
print(x.dtype)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex128


In [46]:
x1 = np.array([1,2,3], dtype=int)
x2 = np.array([5.2,2.8,3.5], dtype=float)

print(x1+x2)
print((x1+x2).dtype)

[6.2 4.8 6.5]
float64


In [47]:
x = np.sqrt(np.array([-1,9,4], dtype=float))
print(x)
print(x.dtype)

[nan  3.  2.]
float64


<ipython-input-47-c84e96242d1d>:1: RuntimeWarning: invalid value encountered in sqrt
  x = np.sqrt(np.array([-1,9,4], dtype=float))


In [48]:
x = np.sqrt(np.array([-1,9,4], dtype=complex))
print(x)
print(x.dtype)

[0.+1.j 3.+0.j 2.+0.j]
complex128


In [51]:
print(x.real)
print(x.imag)
print((x.real).dtype)
print((x.imag).dtype)

[0. 3. 2.]
[1. 0. 0.]
float64
float64


In [52]:
# çalıştığımız ndarray i kaydetmek için.
x = np.array([5,9,12.5,18])
np.save("ndarray_1",x)  #dosya ismi, kaydetmek istediğim ndarray ismi


In [54]:
# kaydettiğimiz dosyası çagırmak için.
y = np.load("ndarray_1.npy")
print(y.shape)

(4,)


In [56]:
x = np.array([3,9,8])
print(x)
print(x.dtype)
print(type(x))

[3 9 8]
int32
<class 'numpy.ndarray'>


# np.zeros     np.ones

In [60]:
x1 = np.zeros(4)
print(x1)
print(x1.dtype)

[0. 0. 0. 0.]
float64


In [61]:
y1 = np.ones(4)
print(y1)
print(y1.dtype)

[1. 1. 1. 1.]
float64


In [62]:
x2=np.zeros((2,3,4),dtype=int)    # dış listenin içinde 2 tane, bunların içinde de 3*4 lük iki matriks var. 
print(x2)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [63]:
y2=np.ones((3,2),dtype=int)    
print(y2)

[[1 1]
 [1 1]
 [1 1]]


In [ ]:
# Numpy tek başına bir şeye yaramaz. Buraya gelecek olan veri önemi olandır.

In [ ]:
# np.full()  ile oluşturduğumuz matrikslerin içine sabit 10 değerini atadık.

In [65]:
x = np.full((2,3),10)
print(x)
print(x.dtype)   #atanan değerinin veri tipini alır.

[[10 10 10]
 [10 10 10]]
int32


In [66]:
x = np.full((2,3),10.0)
print(x)
print(x.dtype)

[[10. 10. 10.]
 [10. 10. 10.]]
float64


In [67]:
y = 10.0*np.ones((2,3))
z= 10.0+np.zeros((2,3))
print(y)
print(z)

[[10. 10. 10.]
 [10. 10. 10.]]
[[10. 10. 10.]
 [10. 10. 10.]]


In [ ]:
# np.empty()  içine default değer atayarak bir ndarray oluşturur.

In [68]:
x = np.empty((2,2))
print(x)

[[ 5.   9. ]
 [12.5 18. ]]


In [69]:
x.fill(3)
print(x)

[[3. 3.]
 [3. 3.]]


In [ ]:
# np.eye()  birim matris oluşturur.

In [71]:
x = np.eye(4)    # t*4 lük diagonal değerleri 1 diğerleri 0 olan matris oluşturur.
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [74]:
y = np.eye(6,4)   # eye fonksiyonunda tekrar parantez içine alarak  tupleye çevirmeye gerek yok.
print(y)   #görüldüğü gibi 4*4 ten sonra birim matris oluşmuyor.

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [76]:
x = np.eye(6)
print(x)
print()
y = np.eye(6, k=1)  # diagonali +1 birim yukarı alır.
print(y)
print()
z = np.eye(6, k=-2)  # diagonali -2 birim aşağı alır.
print(z)
print()

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]



In [77]:
x = np.identity(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# np.diag()

In [78]:
x = np.diag([4,7,11,3])   # verilen değerleri matrisin her bir satırına diagonal olarak atıyor.
print(x) 

[[ 4  0  0  0]
 [ 0  7  0  0]
 [ 0  0 11  0]
 [ 0  0  0  3]]


In [ ]:
# np.arange() son karakter dahil değil. Matematikte yarı açık model denir.

In [79]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [80]:
y = np.arange(4,9)
print(y)

[4 5 6 7 8]


In [82]:
z = np.arange(3,23,4)
print(z)

[ 3  7 11 15 19]


In [84]:
# np.linspace()

In [85]:
import numpy as np

x = np.linspace(0,15,10)
print(x)

[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.         11.66666667 13.33333333 15.        ]


In [86]:
x = np.linspace(0,15)   # kaç tane eleman olacağı yazılmazsa default olarak 50 atar.
print(x)

[ 0.          0.30612245  0.6122449   0.91836735  1.2244898   1.53061224
  1.83673469  2.14285714  2.44897959  2.75510204  3.06122449  3.36734694
  3.67346939  3.97959184  4.28571429  4.59183673  4.89795918  5.20408163
  5.51020408  5.81632653  6.12244898  6.42857143  6.73469388  7.04081633
  7.34693878  7.65306122  7.95918367  8.26530612  8.57142857  8.87755102
  9.18367347  9.48979592  9.79591837 10.10204082 10.40816327 10.71428571
 11.02040816 11.32653061 11.63265306 11.93877551 12.24489796 12.55102041
 12.85714286 13.16326531 13.46938776 13.7755102  14.08163265 14.3877551
 14.69387755 15.        ]


In [87]:
x = np.linspace(0,15, endpoint=False)   
print(x)

[ 0.   0.3  0.6  0.9  1.2  1.5  1.8  2.1  2.4  2.7  3.   3.3  3.6  3.9
  4.2  4.5  4.8  5.1  5.4  5.7  6.   6.3  6.6  6.9  7.2  7.5  7.8  8.1
  8.4  8.7  9.   9.3  9.6  9.9 10.2 10.5 10.8 11.1 11.4 11.7 12.  12.3
 12.6 12.9 13.2 13.5 13.8 14.1 14.4 14.7]


In [ ]:
# np.reshape()

In [88]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [89]:
x = np.reshape(x, (4,5))  #  yeni bir formatta ndarray oluşturmak istediğimizde bunun şeklini giriyoruzb
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [90]:
x = np.reshape(x,(5,5))  # 25 elemana ihtiyaç var ancak bizde 20 eleman olduğundan hata verdi.
print(x)

ValueError: cannot reshape array of size 20 into shape (5,5)

In [91]:
x = np.arange(32)
print(x)
print()

y= np.reshape(x,(2,4,4))
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]


In [92]:
x = np.linspace(0,19,20)
print(x)
print()

y = np.reshape(x,(2,10))   # 2 satir 10 sütun olan bir matris çevirir.
print(y)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]


In [93]:
z = np.linspace(0,19,20).reshape(2,10)
print(z)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]


In [ ]:
# random.random  [0,1]

In [94]:
x = np.random.random((2,3))
print(x)

[[0.0052393  0.27487161 0.41490886]
 [0.20539686 0.97720419 0.32180097]]


In [ ]:
# random.randint

In [95]:
x = np.random.randint(3,12,size=(3,2)) # 3 ile 12(dahil değil) arasında rastgele değer alarak 3*2 lik matris verir.
print(x)

[[ 5  5]
 [11  3]
 [ 7  6]]


In [101]:
x = np.arange(5)
print(x)
print(x[0])
print(x[2])
print(x[5-1])
print(x[-1])
print(x[-2])
print(x[-5])

[0 1 2 3 4]
0
2
4
4
3
0


In [103]:
x[2] = 200
print(x)
print(x[2])

[  0   1 200   3   4]
200


In [106]:
x = np.arange(12).reshape(3,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [107]:
print(x[0,0])

0


In [108]:
print(x[2,3])

11


In [112]:
x = np.arange(5,10)
print(x)

[5 6 7 8 9]


In [113]:
y = np.delete(x,[0,1])  # 0 ve 1. elemanlarını siliyor.
print(y)
print(x)  #bu durumda orjinal değişmiyor. Bunun için y yerine x e atama yapmamız lazım.

[7 8 9]
[5 6 7 8 9]


In [ ]:
# axis = 0 row-satır   axis = 1 column -sütun

In [115]:
x = np.arange(16).reshape(4,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [116]:
x = np.delete(x,1,axis=0)  # axis 0 olduğundan o satır gitti.
print(x)

[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]


In [117]:
x = np.delete(x,[0,2],axis=1) # axis 1 olduğundan bu iki sütun gitti.
print(x)

[[ 1  3]
 [ 9 11]
 [13 15]]


In [ ]:
# np.append  fonk kullanmak için matrislerin şekillerin birbirine uygun olması gerekir.

In [118]:
x = np.arange(5)
print(x)
x = np.append(x, 100)
print(x)

[0 1 2 3 4]
[  0   1   2   3   4 100]


In [119]:
x = np.append(x, [200,300])
print(x)

[  0   1   2   3   4 100 200 300]


In [6]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
import numpy as np
x = np.append([[100,200,300]],axis=0)
print(x)

TypeError: _append_dispatcher() missing 1 required positional argument: 'values'

In [8]:
x = np.append(x,[[100,200,300]],axis=0)
print(x)

[[  0   1   2]
 [  3   4   5]
 [  6   7   8]
 [100 200 300]]


In [9]:
x = np.append(x,[[10],[20],[30],[40]],axis=1)
print(x)

[[  0   1   2  10]
 [  3   4   5  20]
 [  6   7   8  30]
 [100 200 300  40]]


In [ ]:
# np.insert --> np.insert(ndarray, index,element,axis) ile aralara ekleme yapabiliriz.

In [10]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [11]:
x = np.insert(x,0, 10)
print(x)

[10  0  1  2  3  4]


In [12]:
x = np.insert(x,2,[10,20])
print(x)

[10  0 10 20  1  2  3  4]


In [3]:
import numpy as np
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:

x = np.insert(x,1,[100,200,300],axis=0)
print(x)

[[  0   1   2]
 [100 200 300]
 [  3   4   5]
 [  6   7   8]]


In [5]:
x = np.insert(x,0,[10,20,30,40],axis=1)
print(x)

[[ 10   0   1   2]
 [ 20 100 200 300]
 [ 30   3   4   5]
 [ 40   6   7   8]]


In [ ]:
# np.stack

In [7]:
x = np.arange(3)
print(x)

[0 1 2]


In [8]:
y = np.arange(9).reshape(3,3)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
z = np.vstack((x,y))  #vertical yani dikey iliştirme
print(z)

[[0 1 2]
 [0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
t = np.hstack((x,y))   #horizontal yani yatay iliştirme. Burada x y ye ekleneceğinden dolayı y nin şeklini değiştirmeliyiz.
print(t)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [11]:
t = np.hstack((x,y.reshape(9,))) 
print(t)

[0 1 2 0 1 2 3 4 5 6 7 8]


In [13]:
x = np.arange(3)
print(x)

y = np.arange(9).reshape(3,3)
print(y)

y = y.reshape((9,))
t = np.hstack((x,y))
print(t)

[0 1 2]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 0 1 2 3 4 5 6 7 8]


In [14]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
print(x[2:6])

[2 3 4 5]


In [16]:
print(x[4:])

[4 5 6 7 8 9]


In [17]:
print(x[:7])

[0 1 2 3 4 5 6]


In [18]:
print(x[:-1])

[0 1 2 3 4 5 6 7 8]


In [19]:
print(x[4:-2])

[4 5 6 7]


In [22]:
print(x[-4:-2])

[6 7]


In [26]:
x = np.arange(25).reshape(5,5)
print(x)
print()
y = x[0:3, 1:4]  # 0,1,2 satırları ve 1,2,3 sütunları alıyoruz.
print(y)
print()
z = x[2:]  # 2 ve sonraki satırları alıyoruz. Sütunlar ile ilgili bir husus olmadğından hepsini alıyoruz.
print(z)
print()
t = x[::]  # satır ve sütünlar ile ilgili bir kısıtlama yok. Hepsini aldık.
print(t)
print()
v = x[:, 3:] # tüm satırları ve 3 den sonraki sütunları alıyoruz.
print(v)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]


In [27]:
x = np.arange(9).reshape(3,3)
print(x)
print()
y = x[1:2,0:2]   # 1. satırı ve 0,1 sütunları alıyoruz.
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[3 4]]


In [28]:
y [0,0] = 100
print(y)

[[100   4]]


In [29]:
print(x)

[[  0   1   2]
 [100   4   5]
 [  6   7   8]]


In [30]:
print(np.shares_memory(x,y))   # x ve y aynı memory paylaştığını gösterir.

# hafızamızda bir alan tutuyoruz. slicing işlemi yaptıktan aynı ndarray in farklı alanlarını tutuyorlar. 
# Herhangi birdeğişiklik yapılınca ilk ndarray in de görünümünü değiştiriyoruz.

True


In [35]:
x = np.arange(9).reshape(3,3)
print(x)
print()
y = np.copy(x[1:2,0:2])
print(y)
print()
print(np.shares_memory(x,y))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[3 4]]

False


In [36]:
y[0,0] = 100
print(y)
print(x)

[[100   4]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Yukarıdaki iki farklı yöntemde görüldüğü gibi slicing metodunu kullanarak yaptığımızda x ve y aynı hafızayı kullanırken, 
# diğer yöntemde aynı hafızayı kullanmadığından yapılan değişiklikler x de yansımıyor.
# slicing de aynı ndarrayın farklı görsellerini oluştururken
# copy de farklı ndarrayler oluşturuyoruz.

In [39]:
z = x[1:2,1:2].copy()
print(z)
print()
print(x)
print()
print(np.shares_memory(x,z))

[[4]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

False


In [40]:
import numpy as np

In [41]:
x = np.linspace(1,21,11)
print(x)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21.]


In [42]:
y = np.array([2,4,7])
print(y)

[2 4 7]


In [43]:
print(x[y])  # x ndarrayimizi başka bir y ndarrayi ile dilimledik.

[ 5.  9. 15.]


In [47]:
x = np.arange(25).reshape(5,5)
print(x)
print()
y= np.array([1,2])
print(y)
print()
print(x[y,:]) # 1.ve 2. satırları alıyoruz ve sütunların tamamını alıyoruz.
print()
print(x[:,y]) # satırların tamamını alıyoruz, sütunların 1. ve 2. yi alıyoruz.
# burada başka bir ndarray ile slicing yapıyoruz.

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[1 2]

[[ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]]


In [48]:
z = x[y,:]
print(x)
z[0,0] = 100
print(z)
print(x)
print(np.shares_memory(x,z))

# bir ndarrayin bir alt kümesine başka bir ndarray yardımı ile 
# ulaşabiliyorsam buna fancy indexing denir. Burada yapılan değişiklikten orjinal ndarray etkilenmiyor.

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[100   6   7   8   9]
 [ 10  11  12  13  14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
False


In [51]:
x = np.arange(10)
print(x)
print()
print(x[x % 2 == 0]) # x in elemanlarından 2 ye bölünebilenleri gönderir.
z = x[(x % 2 == 0)]
print(z)
z[0] = 100
print(z)
print()
print(x)
# boolean indexing de fancy indexing yapılan değişikler orjinal ndarray i etkilemiyor.

[0 1 2 3 4 5 6 7 8 9]

[0 2 4 6 8]
[0 2 4 6 8]
[100   2   4   6   8]

[0 1 2 3 4 5 6 7 8 9]


In [53]:
x = np.random.randint(10, size=10) #10 hariç bu arada bize 10 tane rastgele sayı verir.
y = np.random.randint(10, size=10)

print(x)
print(y)
print(x>y)  #boolean olarak bunu sonucunu her bir eleman için veriyor.
print(type(x>y))
print((x>y).dtype)

print()
print(np.all(x>y))  # burada x in elemanlarının tamamı y ninkilerden büyükse true döner.
print(np.any(x>y))  # burada x in elemanlarından sadece 1 tane olsa bile y ninkilerden büyükse true döner.


[6 0 9 3 9 9 2 1 8 5]
[5 6 2 3 3 1 7 5 2 0]
[ True False  True False  True  True False False  True  True]
<class 'numpy.ndarray'>
bool

False
True


In [56]:
x = np.linspace(1,21,11)
print(x)
mask = (x % 3 == 0)
print(mask)
print(type(mask))
print(x[mask])  # x in mask kuralına uyan elemanlarını listele.

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21.]
[False  True False False  True False False  True False False  True]
<class 'numpy.ndarray'>
[ 3.  9. 15. 21.]


In [59]:
x[mask] = -3  #kurala uyanları -3 olarak gösteriyor.
print(x)

[ 1. -3.  5.  7. -3. 11. 13. -3. 17. 19. -3.]


In [62]:
x = np.array([2,5,3,6,9])
y = np.array([6,1,8,7,3])

In [63]:
z = np.intersect1d(x,y)  #iki ndarray da ortak olanları verir.
print(z)
print(type(z))

[3 6]
<class 'numpy.ndarray'>


In [64]:
z = np.setdiff1d(x,y)  # x de olup y de olmayanları verir.
print(z)
print(type(z))

[2 5 9]
<class 'numpy.ndarray'>


In [65]:
z = np.union1d(x,y)  # x ve y nin birleşimini verir. 
print(z)
print(type(z))

[1 2 3 5 6 7 8 9]
<class 'numpy.ndarray'>


In [66]:
z = np.in1d(x,y)  # x de olan bir elemanın y içinde olup almadığına bakar.
print(z)
print(type(z))

[False False  True  True False]
<class 'numpy.ndarray'>


In [67]:
x = np.array([2,5,3,6,9,4,3,6,5,0])
print(np.unique(x))

[0 2 3 4 5 6 9]


In [ ]:
# sort

In [73]:
x = np.random.randint(1,10,size=(10,))
print(x)
print()
print(np.sort(x))  # burada sort fonksiyon şeklinde. Bu durumda sadece olduğu yerde değişiklik yapıyor.
print()
print(x)
print()

[8 9 3 8 5 9 1 3 1 7]

[1 1 3 3 5 7 8 8 9 9]

[8 9 3 8 5 9 1 3 1 7]



In [76]:
y = np.random.randint(1,10,size=(10,))
print(y)
y.sort()
print()
print(y)

[2 6 4 2 4 6 9 5 9 7]

[2 2 4 4 5 6 6 7 9 9]


In [77]:
x = np.random.randint(1,10,size=(5,5))
print(x)
print()
print(np.sort(x,axis=0))  # sütunlara göre sıralar.
print()
print(np.sort(x,axis=1))  # satırlara göre sıralar.

[[8 9 4 9 7]
 [3 2 6 3 8]
 [8 8 2 8 9]
 [9 1 7 4 4]
 [6 7 3 9 7]]

[[3 1 2 3 4]
 [6 2 3 4 7]
 [8 7 4 8 7]
 [8 8 6 9 8]
 [9 9 7 9 9]]

[[4 7 8 9 9]
 [2 3 3 6 8]
 [2 8 8 8 9]
 [1 4 4 7 9]
 [3 6 7 7 9]]


In [ ]:
# element-wise, array-wise

In [4]:
import numpy as np
x = np.random.randint(1,10,size=(5,))
print(x)

[4 1 7 4 3]


In [5]:
y = np.random.randint(1,10,size=(5,))
print(y)

[3 4 7 5 4]


In [6]:
print(x+y)  # toplama işlemi bu şekilde olabileceği gibi aşağıdaki gibide olabilir.

[ 7  5 14  9  7]


In [7]:
print(np.add(x,y))

[ 7  5 14  9  7]


In [8]:
print(np.subtract(x,y))

[ 1 -3  0 -1 -1]


In [10]:
print(np.multiply(x,y))

[12  4 49 20 12]


In [11]:
print(np.divide(x,y))

[1.33333333 0.25       1.         0.8        0.75      ]


In [3]:
import numpy as np
x = np.random.randint(1,10,size=(5,))
print(x)

[6 7 9 2 7]


In [4]:
y = np.random.randint(1,10,size=(5,))
print(y)

[2 2 4 2 2]


In [5]:
print(x == y)

[False False False  True False]


In [6]:
y = np.random.randint(1,10,size=(6,))
print(y)

[9 4 9 8 6 2]


In [7]:
print(x == y)

False


<ipython-input-7-d56506f55da8>:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print(x == y)


In [8]:
print(x+y)

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [9]:
print(np.array_equal(x,y))

False


In [12]:
x = np.arange(10)
y = np.arange(10)

print(np.array_equal(x,y))

True


In [13]:
print(np.sqrt(x))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [16]:
print(np.power(x,2))

[ 0  1  4  9 16 25 36 49 64 81]


In [20]:
x = np.random.randint(1,10,size=(9,)).reshape(3,3)
print(x)

[[4 9 9]
 [1 1 8]
 [5 2 2]]


In [21]:
print(np.sum(x))

41


In [25]:
print(x)
print(np.sum(x))  # tüm toplamı verir.
print(x.sum(axis=0))   #sütun toplamlarını yazar.
print(x.sum(axis=1))   # satır toplamlarını yazar
print(x.min()) 
print(x.max()) 
print(x.argmin())   # en küçük elemanın index numarasını döner.
print(x.argmax())   # en büyük elemanın index numarasını döner.

[[4 9 9]
 [1 1 8]
 [5 2 2]]
41
[10 12 19]
[22 10  9]
1
9
3
1


In [26]:
import numpy as np

In [27]:
x = np.random.randint(1,10,size=(8,))

In [28]:
print(x) 
print()
print(x.mean())  # aritmetik ortalamasıni verir.    
print()
print(np.median(x))  # median ı verir.       # 2 5 6 6 6 8 9 9
print()
print(x.std())  # standart sapmasını verir.her bir elemanı aritmetik ortalamadın çıkarıp kareleri taplamını eleman sayısına bölüyoruz. çıkan sonuç stan.sapmanın karesi oluyor.

[9 6 2 6 5 9 8 6]

6.375

6.0

2.1758618981911515


In [34]:
y = np.random.randint(1,10,size=(4,3))

In [35]:
print(y) 
print()
print(y.mean(axis=0))  # sütunların aritmetik ortalamasını alıyoruz.
print()
print(np.median(y,axis=1)) # satırların median ı buluyoruz.
print()
print(y.std(axis=0))  # sütunların standart sapmasını buluyoruz.

[[1 3 9]
 [3 1 6]
 [9 9 6]
 [3 1 2]]

[4.   3.5  5.75]

[3. 3. 9. 2.]

[3.         3.27871926 2.48746859]


In [38]:
x = np.random.randint(1,10,size=(3,2))
print(x)

[[9 4]
 [6 7]
 [9 4]]


In [39]:
# y = np.random.randint(1,10,size=(3,2))
# print(y)

[[6 2]
 [1 9]
 [3 9]]


In [40]:
print(x+y)

[[15  6]
 [ 7 16]
 [12 13]]


In [48]:
x = np.random.randint(1,10,size=(1,))
print(x)
print()
y = np.random.randint(1,10,size=(3,2))
print(y)
print()
print(x+y) #broadcasting örnek olarak verilebilir. 

[9]

[[3 3]
 [2 1]
 [9 4]]

[[12 12]
 [11 10]
 [18 13]]


In [46]:
x = np.random.randint(1,10,size=(3,))
print(x)
print()
y = np.random.randint(1,10,size=(3,2))
print(y)
print()
print(x+y)

[4 3 6]

[[6 7]
 [2 6]
 [3 4]]



ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

# SORULAR

In [49]:
x = np.zeros(5)
y = np.ones(5)

print(x)
print()
print(y)

[0. 0. 0. 0. 0.]

[1. 1. 1. 1. 1.]


In [51]:
x = np.arange(7,42,2)
print(x)

[ 7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41]


In [52]:
x = np.random.randint(1,10,16).reshape(4,4)
print(x)

[[4 4 7 2]
 [4 7 6 9]
 [3 4 4 8]
 [7 9 4 3]]


In [55]:
x = np.linspace(0.1,1,10)
print(x)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [59]:
x = np.arange(0,25).reshape(5,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [60]:
y = x[1:3,2:4]
print(y)

[[ 7  8]
 [12 13]]


In [65]:
x = np.arange(1,17).reshape(4,4)
print(x)
print()
y = x[x%2==0].reshape(2,4)
print(y)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 2  4  6  8]
 [10 12 14 16]]


# Sinemaya giriş ücreti öğrenciler için 5 TL olmayanlar için 10 TL. 100 kişi için 700 TL toplandığına göre öğrenci sayısı kaçtır? 
# (x1+x2=100, 5x1+10x2=700)

In [67]:
a = np.array([[1,1],[5,10]])  # Bu matrisin ilk satırı x1 ve x2 için, ikinci satır 5x1 ve 10x2 için.
print(a)
print()

b = np.array([100,700])  # Bu katsayılara ait denklemlerin sonucunu yazdık.
print(b)
print()

x = np.linalg.solve(a,b)   # linalg ile çözümü buldum.
print(x) 

[[ 1  1]
 [ 5 10]]

[100 700]

[60. 40.]


In [71]:
x = np.random.randint(1,5,6).reshape(3,2)
print(x)
print()
y = np.random.randint(1,5,6).reshape(2,3)
print(y)
print()
print(np.dot(x,y))

[[4 3]
 [3 1]
 [4 3]]

[[1 2 1]
 [3 1 1]]

[[13 11  7]
 [ 6  7  4]
 [13 11  7]]
