In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


'C:\Users\HP\anaconda3\envs\hot' is not recognized as an internal or external command,
operable program or batch file.


In [2]:
conda install numpy


Note: you may need to restart the kernel to use updated packages.


'conda' is not recognized as an internal or external command,
operable program or batch file.


In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
np.__version__

'1.20.1'

In [4]:
import time

In [5]:
import sys

In [6]:
l = range(1000)
print(sys.getsizeof(5)*len(l))

array = np.arange(1000)
print(array.size*array.itemsize)

28000
4000


In [5]:
import numpy as np
import time
import sys

SIZE = 100000

l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

# python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took:", (time.time()-start)*1000)

# numpy array
start = time.time()
result = a1 + a2
print("numpy took:", (time.time()-start)*1000)


python list took: 9.46950912475586
numpy took: 1.9943714141845703


In [7]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

In [8]:
a1+a2

array([5, 7, 9])

In [9]:
a2-a1

array([3, 3, 3])

In [10]:
a1/a2

array([0.25, 0.4 , 0.5 ])

In [11]:
a1*a2

array([ 4, 10, 18])

In [12]:
import numpy as np

In [13]:
a = np.array([5,6,9])

In [14]:
a[0]

5

In [15]:
a[1]

6

In [19]:
a = np.array([[1,2],[3,4],[5,6]])
a.ndim

2

In [20]:
a = np.array([5,6,9])
a.ndim

1

In [21]:
a.itemsize

4

In [22]:
a.dtype

dtype('int32')

In [23]:
a = np.array([[1,2],[3,4],[5,6]],dtype = np.float64)
a.itemsize

8

In [24]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [25]:
a.size

6

In [26]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [27]:
a.shape

(3, 2)

In [28]:
a = np.array([[1,2],[3,4],[5,6]],dtype = complex)
a.itemsize

16

In [29]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [30]:
import numpy as np

In [32]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
l = range(5)
l

range(0, 5)

In [36]:
l[0]

0

In [37]:
l[1]

1

In [38]:
np.arange(1,5)

array([1, 2, 3, 4])

In [39]:
np.arange(1,5,2)

array([1, 3])

In [40]:
np.arange(1,5,-1)

array([], dtype=int32)

In [41]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [42]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [43]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [45]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
a.shape

(3, 2)

In [47]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [49]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [50]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
a.min()

1

In [52]:
a.max()

6

In [53]:
a.sum()

21

In [54]:
a.sum(axis=0)

array([ 9, 12])

In [55]:
a.sum(axis=1)

array([ 3,  7, 11])

In [56]:
a.sqrt()

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [57]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [58]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
np.std(a)

1.707825127659933

In [60]:
a = np.array([[1,1],[0,1]])

In [61]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [62]:
a

array([[1, 2],
       [3, 4]])

In [63]:
a+b

array([[ 6,  8],
       [10, 12]])

In [64]:
a*b

array([[ 5, 12],
       [21, 32]])

In [65]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [66]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [67]:
import numpy as np
np.random.randint(1,10)

5

In [70]:
import numpy as np
a = np.array([[5,6,9]])

In [71]:
a[0]

array([5, 6, 9])

In [74]:
a = np.array([5,6,9])

In [75]:
a[0]

5

In [79]:
a = np.array([5,6,9])

In [80]:
a.ndim

1

In [81]:
a = np.array([[1,2],[3,4],[5,6]])
a.ndim

2

In [82]:
a.itemsize

4

In [83]:
a.dtype

dtype('int32')

In [84]:
a[0,3:5]

array([], dtype=int32)

In [85]:
import numpy as np
n = [6,7,8]
n[0:2]

[6, 7]

In [86]:
n[-1]

8

In [87]:
a = np.array([6,7,8])
a[0:2]

array([6, 7])

In [88]:
a[-1]

8

In [89]:
a = np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [90]:
a[1,2]

3

In [92]:
a[0:2,2]

array([8, 3])

In [93]:
a[-]1

SyntaxError: invalid syntax (<ipython-input-93-c09de96b2363>, line 1)

In [94]:
a[-1]

array([9, 3, 2])

In [96]:
a[-1,0:2]

array([9, 3])

In [97]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [98]:
a = np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [99]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [100]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [101]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [102]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [103]:
np.vstack(a,b)

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [104]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [106]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [107]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [108]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [111]:
result=np.hsplit(a,3)

In [112]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [113]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [114]:
result=np.vsplit(a,2)
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [115]:
result[1]        

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [116]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [117]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [118]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [119]:
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [122]:
import numpy as np
arr = np.arange(0,11)

arr[2:5]

array([2, 3, 4])

In [123]:
import numpy as np
arr = np.arange(1,8)
arr[arr>4]

array([5, 6, 7])

In [124]:
import numpy as np
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d
arr_2d[0,2]

15

In [125]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [126]:
a+2

array([3, 4, 5, 6])

In [127]:
a-2

array([-1,  0,  1,  2])

In [128]:
a*2

array([2, 4, 6, 8])

In [129]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [130]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [131]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [132]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [133]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [137]:
a = np.ones((2,3))
print(a)
b =np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [138]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [141]:
#find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
# Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

In [142]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [143]:
np.min(stats)

1

In [145]:
np.max(stats,axis=0)

array([4, 5, 6])

In [146]:
np.max(stats,axis=1)

array([3, 6])

In [147]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [148]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [149]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [150]:
after = before.reshape((2,3))
print(after)

ValueError: cannot reshape array of size 8 into shape (2,3)

In [151]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [154]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [155]:
import numpy as np
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1)-np.max(arr_2)

array([-4., -3., -2., -1.,  0.])

In [156]:
import numpy as np
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1)-

array([2., 3., 4., 5., 6.])

In [157]:
import numpy as np
arr_1 = np.array([5,6,7])
arr_2 = np.array([4,5,6])
arr_1-arr_2

array([1, 1, 1])

In [158]:
import numpy as np
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [159]:
arr_2d[2,1]

40

In [160]:
import numpy as np
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d

arr_2d[:1,1:]

array([[10, 15]])

In [161]:
import numpy as np
arr = np.arange(1,6)
arr[arr>3]

array([4, 5])

In [162]:
import numpy as np
arr_1 = np.arange(0,10)
arr_2 = arr_1 * 3
np.max(arr_2)

27

In [163]:
import numpy as np
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1)-arr_2

array([0., 0., 0., 0., 0.])

In [164]:
import numpy as np
arr=np.arange(1,37)
arr.shape

(36,)