___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [1]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [2]:
my_list=[5,10,15,20,25]
np.array(my_list)

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [4]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [5]:
np.ones((4,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [6]:
np.ones((4,4),dtype=int)*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [10]:
np.full((4,4),7)


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [12]:
np.arange(2,18,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [13]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [19]:
x = np.linspace(0,24,25).reshape(5,5)
np.array(x,dtype=int)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create 5 random number with numpy

In [33]:
np.random.random((5,))

array([0.47797814, 0.07946813, 0.41398697, 0.14941751, 0.44760009])

#### 11. Create random normal distributed 5x5 array

In [34]:
np.random.randn(5,5)

array([[ 0.87415443, -0.8589215 , -0.37119612,  0.12992729, -0.66718272],
       [ 0.68138622, -2.09202806, -2.07605387, -0.24804288,  0.54017383],
       [-1.03449672,  0.64210693, -1.07355558, -0.05899147,  0.41460989],
       [ 0.48245523, -0.31316749, -1.08371076, -0.55793316,  0.41837381],
       [-1.07456206,  0.52085193, -1.86227359,  0.1431116 , -1.33771454]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [37]:
np.random.randint(20,50,size=(3,4))

array([[44, 21, 40, 44],
       [21, 31, 28, 49],
       [32, 37, 22, 33]])

#### 13. Reshape the array below with shape 6x8

In [42]:
ranarr = np.random.randint(0, 60, 48)
ranarr

array([43,  5, 22, 51, 36, 40, 22, 35, 13,  6, 44, 16, 53,  2, 14, 30, 54,
        0, 34, 50, 42, 20,  0,  0, 29,  7, 47, 59, 42,  1, 52, 42, 30, 55,
       36, 17, 12, 19, 10,  9, 39, 49, 56, 47, 37, 11, 49, 13])

In [2]:
ranarr.reshape(6,8)

NameError: name 'ranarr' is not defined

In [1]:
ranarr.reshape(-1,8)

NameError: name 'ranarr' is not defined

## Numpy Indexing and Selection


In [28]:
#Create array below
import numpy as np
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [29]:
a = np.arange(1,17).reshape(4,4)
a[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [30]:
a[::,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [31]:
a[1:2,::2]

array([[5, 7]])

#### 17.Assign 77 to every cell in 3rd column.

In [32]:

a[:,2:3] = 77
a

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 1st row 0 column, 3th row 2nd column.

In [58]:
satır = np.array([1,3])
sütun = np.array([0,2])
a[satır,sütun]     # a[[1,3],[0,2]]

array([ 5, 77])

In [65]:
a[1:2:,0:1:][3::,2:3:]

array([], shape=(0, 0), dtype=int32)

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [60]:
a[1::2,0::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [74]:
arr1 = a[(a<10)]
arr1

array([1, 2, 4, 5, 6, 8, 9])

In [76]:
arr2 = a[(a>12)]
arr2

array([77, 77, 77, 13, 14, 77, 16])

In [77]:
np.add(arr1,arr2)

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [79]:
np.std(a)

30.004166377354995

#### 22. Get the sum of second column from array above

In [105]:
#print array here

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [81]:
np.sum(a[2:3,0:])

108

#### 23. Get the median,mean and std of 3rd column from array above

In [117]:
#median
np.median(a[::,3::])

10.5

In [83]:
#mean
np.mean(a[::,3::])

10.0

In [84]:
#std
np.std(a[::,3::])

4.47213595499958

# Pandas Section

In [1]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [2]:
df = pd.read_csv("Salaries/Salaries.csv", sep=",")
df.head(5)

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [4]:
df.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

**How many different year value are there**

In [5]:
df["Year"].value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [6]:
df["TotalPay"].max()

567595.43

In [7]:
avg = df["TotalPay"].mean()
avg

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [8]:
type(df[df.TotalPay > avg])


pandas.core.frame.DataFrame

In [9]:
len(df[df["TotalPay"]>avg])


69489

**How much does ALBERT PARDINI make (including benefits)?**

In [10]:

fil = df.loc[df["EmployeeName"]=="ALBERT PARDINI"]
fil["TotalPayBenefits"]


2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

In [11]:
lowest = df["TotalPayBenefits"].min()
lowest

-618.13

In [12]:
a = df.loc[df["TotalPayBenefits"]==lowest]
a.iloc[:,0:2]

Id EmployeeName
148653  148654    Joe Lopez

**What are the unique Jobs in dataset?**

In [13]:
df["JobTitle"].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [39]:
import pandas as pd
a = df["JobTitle"].value_counts()
a.tail()

ORTHOPEDIC TECHNICIAN I                1
SUPERVISING PARTS STOREKEEPER          1
STATISTICIAN                           1
DIRECTOR, FISCAL SERVICES              1
ASSISTANT DIRECTOR, LOG CABIN RANCH    1
Name: JobTitle, dtype: int64

In [21]:
b = df["JobTitle"].value_counts(ascending= True)
b

Cashier 3                          1
LEGISLATIVE CALENDAR CLERK         1
SENIOR PLAN CHECKER                1
SPECIAL ASSISTANT XVIII            1
DIRECTOR, PROBATION SERVICES       1
                                ... 
Police Officer 3                2421
Public Svc Aide-Public Works    2518
Registered Nurse                3736
Special Nurse                   4389
Transit Operator                7036
Name: JobTitle, Length: 2159, dtype: int64

**How many people earned more than avg in 2012**

In [16]:
avg = df["TotalPay"].mean()
avg

74768.321971703

In [41]:
avg1=df.groupby(["Year"])
a = avg1.get_group(2012)
b = (a["TotalPay"])>(a["TotalPay"].mean())
b.value_counts()

False    19822
True     16944
Name: TotalPay, dtype: int64

In [37]:
avg1=df.groupby(["Year"])
a = avg1.get_group(2012)
b = (a["TotalPay"])>avg
b.value_counts().

False    20050
True     16716
Name: TotalPay, dtype: int64

In [27]:
count = df[["EmployeeName","Year","TotalPay"]][(df["TotalPay"]>avg) & (df["Year"]==2012)]
count

EmployeeName  Year   TotalPay
36159      Gary Altenberg  2012  362844.66
36160        Gregory Suhr  2012  321552.11
36161          Khoa Trinh  2012  336393.73
36162  Joanne Hayes-White  2012  314759.60
36163   Frederick Binkley  2012  337204.86
...                   ...   ...        ...
60070     Leeanne Mercier  2012   75028.74
60463       Carol Pirolli  2012   77993.23
60717      Jocelyn Weiler  2012   77354.06
60733        Diana Edward  2012   77269.21
60900       Mary Ann Hauf  2012   76451.34

[16716 rows x 3 columns]

**How many people have the word Manager in their job title?**

In [76]:
a = df[df["JobTitle"].str.contains("Manager",na=False)].apply(len)

b = df[df["JobTitle"].str.contains("MANAGER",na=False)].apply(len)

print(a)
print()
print(b)
c = a+b
c["JobTitle"]

Id                  3080
EmployeeName        3080
JobTitle            3080
BasePay             3080
OvertimePay         3080
OtherPay            3080
Benefits            3080
TotalPay            3080
TotalPayBenefits    3080
Year                3080
Notes               3080
Agency              3080
Status              3080
dtype: int64

Id                  1030
EmployeeName        1030
JobTitle            1030
BasePay             1030
OvertimePay         1030
OtherPay            1030
Benefits            1030
TotalPay            1030
TotalPayBenefits    1030
Year                1030
Notes               1030
Agency              1030
Status              1030
dtype: int64


4110

In [ ]:
# len(df[df.JobTitle.apply(lambda x: True if "manager" in x.lower() else False)])

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [111]:
a = ["Id","EmployeeName","JobTitle","TotalPay","TotalPayBenefits"]
sal_new = df[a]
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [110]:
a = ["EmployeeName","JobTitle","TotalPay","TotalPayBenefits"]
sal_new = df[a]
sal_new

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

         TotalPay  TotalPayBenefits  
0       567595.43         567595.43  
1       538909.28         538909.28  
2       335279.91         335279.91  
3       332343.61         332343.61  
4       326373.19         326373.19  
...           ...               ...  
148649       0.00              0.00  
148650       0.00              0.00  
148651       0.00              0.00  
148652       0.00              0.00  
148653    -618.13           -618.13  

[148654 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [96]:
avg = df["TotalPay"].mean()
avg

74768.321971703

In [99]:
minx = df["TotalPay"].min()
minx

-618.13

In [102]:
name = df[["EmployeeName","TotalPay"]][(df["TotalPay"] > minx) & df["TotalPay"]<avg]
name

EmployeeName   TotalPay
0          NATHANIEL FORD  567595.43
1            GARY JIMENEZ  538909.28
2          ALBERT PARDINI  335279.91
3       CHRISTOPHER CHONG  332343.61
4         PATRICK GARDNER  326373.19
...                   ...        ...
148649      Roy I Tillery       0.00
148650       Not provided       0.00
148651       Not provided       0.00
148652       Not provided       0.00
148653          Joe Lopez    -618.13

[148654 rows x 2 columns]