In [1]:
import seaborn as sns

In [4]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'geyser',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'tips',
 'titanic']

In [2]:
df = sns.load_dataset("mpg")

In [3]:
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  
0            70     usa  chevrolet chevelle malibu  
1            70     usa          buick skylark 320  
2            70     usa         plymouth satellite  
3            70     usa              amc rebel sst  
4            70     usa                ford torino  
..          ...     ...                        ...  
393          82     usa            ford mustang gl  
394          82  europe                  vw pickup  
395          82     usa              dodge rampage  
396          82     usa                ford ranger  
397          82     usa                 chevy s-10  

[398 rows x 9 columns]

In [5]:
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [6]:
df.shape  # 389 gözlem ve 9 değişken var.

(398, 9)

In [9]:
df.shape[1]

9

In [7]:
df.columns  # değişken isimlerini veriyor.

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [8]:
len(df.columns)

9

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    object 
 8   name          398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB


In [11]:
df.select_dtypes(include=["object"])

origin                       name
0       usa  chevrolet chevelle malibu
1       usa          buick skylark 320
2       usa         plymouth satellite
3       usa              amc rebel sst
4       usa                ford torino
..      ...                        ...
393     usa            ford mustang gl
394  europe                  vw pickup
395     usa              dodge rampage
396     usa                ford ranger
397     usa                 chevy s-10

[398 rows x 2 columns]

In [13]:
df.select_dtypes(exclude=["object"]).head()

mpg  cylinders  displacement  horsepower  weight  acceleration  model_year
0  18.0          8         307.0       130.0    3504          12.0          70
1  15.0          8         350.0       165.0    3693          11.5          70
2  18.0          8         318.0       150.0    3436          11.0          70
3  16.0          8         304.0       150.0    3433          12.0          70
4  17.0          8         302.0       140.0    3449          10.5          70

In [14]:
df.nunique(axis=0)  # her bir değişkendeki unique olarak değerlere kaç tane olduğuna bakıyoruz.

mpg             129
cylinders         5
displacement     82
horsepower       93
weight          351
acceleration     95
model_year       13
origin            3
name            305
dtype: int64

In [15]:
import numpy as np

In [17]:
np.random.seed(101)

population = np.random.randint(0,100,size=100000)

In [18]:
population

array([95, 11, 81, ..., 72, 75, 64])

In [19]:
len(population)

100000

In [20]:
np.random.seed(101)

sample = np.random.choice(population, size=100)

In [21]:
sample

array([48, 99, 63, 36, 99, 38, 76, 63, 91, 53, 75, 62, 23, 13,  8, 83, 10,
       15, 80,  8, 56,  6, 85, 87, 22, 97, 51, 26, 75, 47, 86, 21, 10, 90,
       31, 66, 30, 66, 63,  8, 89, 24, 79, 45,  9,  1, 54, 91, 58,  4, 89,
        1, 38, 55, 21, 28, 43, 26, 23, 85, 98, 52, 19, 99, 56, 16, 87, 10,
       64, 44, 44, 71, 84, 83, 76, 47, 41, 54, 71,  7,  1, 17, 61, 35, 57,
       95, 87, 67, 52, 91, 68, 14, 88, 77, 96, 39,  5, 27, 40, 49])

In [22]:
np.random.seed(51)   # aynı cell içerisinde çalıştırmamız gerekir.

sample = np.random.choice(population, size=100)

In [23]:
sample

array([89, 69,  3, 24, 28,  1, 63, 44, 41, 23,  1, 53, 21, 23, 51, 90, 26,
       54, 84, 83,  9, 64, 42, 15, 65, 37,  3, 29, 96, 90, 47, 73, 92, 87,
       91, 67, 69, 14, 45, 11, 68, 70, 95, 21, 64, 77, 94, 63, 55, 36, 21,
       46, 77, 82, 27, 89, 16, 97, 70, 85, 71, 50, 32, 99, 16, 34, 62, 87,
       48, 37, 46, 25, 53,  4, 58, 18, 59, 68, 68, 90, 23, 56, 17, 86, 24,
       47, 59,  6, 87, 38,  7, 96, 39, 50, 33, 13, 21,  4, 13, 43])

In [24]:
population.mean()

49.41751

In [25]:
sample.mean()

49.57

In [26]:
sample.std()

28.680744411538555

In [27]:
sample_means = []

for i in range(100):
    sample = np.random.choice(population,100)
    sample_means.append(sample.mean())


In [30]:
sample_means  # çektiğimiz 100 lüklerin ortalama değerlerine baktık. Bunların ortalaması ise sample.mean olacaktır.
# sample miktarı ne kadar artarsa population.mean o kadar yakın bir değer ortaya çıkardı.

[51.7,
 51.24,
 50.63,
 52.99,
 44.44,
 51.59,
 51.29,
 43.7,
 46.87,
 46.58,
 45.55,
 53.4,
 46.02,
 49.3,
 46.13,
 47.46,
 46.66,
 49.13,
 52.13,
 45.14,
 46.81,
 48.84,
 45.91,
 48.15,
 53.72,
 46.62,
 47.74,
 47.15,
 47.63,
 46.16,
 50.25,
 49.18,
 48.51,
 49.18,
 47.11,
 50.13,
 47.34,
 47.43,
 49.44,
 52.96,
 41.62,
 52.64,
 43.67,
 48.31,
 50.61,
 48.74,
 46.13,
 55.38,
 51.09,
 46.13,
 51.61,
 47.15,
 48.86,
 49.8,
 48.66,
 47.87,
 46.56,
 47.3,
 44.52,
 50.25,
 53.42,
 50.86,
 49.22,
 52.92,
 51.27,
 51.75,
 49.06,
 54.72,
 45.74,
 52.89,
 52.38,
 44.66,
 48.02,
 49.85,
 51.61,
 50.69,
 45.19,
 50.97,
 49.36,
 49.69,
 52.1,
 49.12,
 45.78,
 45.54,
 47.23,
 49.0,
 44.12,
 51.24,
 50.43,
 51.54,
 50.57,
 44.23,
 52.53,
 48.61,
 49.29,
 48.0,
 55.59,
 50.47,
 45.97,
 50.65]

In [31]:
np.mean(sample_means)

48.953900000000004